{
 "title": "App Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total{})" }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{} / http_request_duration_seconds_count{}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total{}", "legendFormat": "{{handler}}" }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status=~\"2.*\"}) / sum by(handler) (http_requests_total{})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(handler) (http_requests_total{status_code=~\"5.*\"}) / sum by(handler) (http_requests_total{})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "timeseries",
   "description": "App container",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"app\"}",
     "legendFormat": "{{name}} Container"
    }
   ]
  },
  {
   "title": "CPU usage in the last minute",
   "type": "timeseries",
   "description": "App container",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"app\"}[1m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Bytes transmitted over the network ",
   "type": "timeseries",
   "description": "Bytes transmitted over the network by the container per second in the last minute - App service",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{interface=\"eth0\", container_label_com_docker_compose_service=\"app\"}[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Bytes received over the network ",
   "type": "timeseries",
   "description": "Bytes received over the network by the container per second in the last minute - App service",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{interface=\"eth0\", container_label_com_docker_compose_service=\"app\"}[1m])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}